# Utiliza la imagen base de nginx
FROM nginx:latest

# Copia el archivo index.html al directorio por defecto de Nginx
COPY src/index.html /usr/share/nginx/html/index.html

# Exponer el puerto 80 para el tráfico web
EXPOSE 80
